# Generated by Django 4.1.2 on 2022-11-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rental_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rental_price_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
